---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox
  namespace: default
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.proxmox.smartmur.lab`)
      kind: Rule
      services:
        - name: proxmox
          port: 8006
          scheme: https
          passHostHeader: true
    - match: Host(`proxmox.smartmur.lab`)
      kind: Rule
      services:
        - name: proxmox
          port: 8006
          scheme: https
          passHostHeader: true
      middlewares:
        - name: default-headers
  tls:
    secretName: smartmur-tls
