---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
  namespace: portainer
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.portainer.smartmur.lab`) # change me
      kind: Rule
      services:
        - name: portainer
          port: 9443
    - match: Host(`portainer.smartmur.lab`) # change me
      kind: Rule
      services:
        - name: portainer
          port: 9443
          scheme: https
          passHostHeader: true
      middlewares:
        - name: default-headers
  tls:
    secretName: yourdomain-tls # change me
