version: 2
ethernets:
  eth0:
    %{ if ip_type == "dhcp" ~}
    dhcp4: true
    dhcp4-overrides:
      use-dns: true
    %{ else ~}
    addresses:
      - ${ip_address}/${ip_prefix}
    gateway4: ${gateway}
    nameservers:
      addresses: [${dns_servers}]
    %{ endif ~}
